language: node_js
node_js:
  - "8.5.0"
before_script:
  - npm install
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
script: npm run test
sudo: required
addons:
  chrome: stable
