language: node_js
node_js:
  - "8.5.0"
before_script:
  - npm install
script: npm run test
sudo: required
addons:
  chrome: beta
before_install:
  - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"
