module.exports = {
  DB: 'mongodb://localhost/movie_rating_app',
  SECRET: '<secret>',
  FACEBOOK_APP_ID: '<FACEBOOK_APP_ID>',
  FACEBOOK_APP_SECRET: '<FACEBOOK_APP_SECRET>',
  TWITTER_APP_ID: '<TWITTER_APP_ID>',
  TWITTER_APP_SECRET: '<TWITTER_APP_SECRET>',
  GOOGLE_APP_ID: '<GOOGLE_APP_ID>',
  GOOGLE_APP_SECRET: '<GOOGLE_APP_SECRET>',
  LINKEDIN_APP_ID: '<LINKEDIN_APP_ID>',
  LINKEDIN_APP_SECRET: '<LINKEDIN_APP_SECRET>'
}
